### ISSUE TITLE
ExchangeInfo API missing

### ISSUE THREAD

**Issue by EUA** [outlier-1/btcturkapi-python#10]
USDTBTC emir verirken fiyat kayar noktalı olursa yada ondalıklı bir birim alırken fazla sayıda basamak bulunursa INVALID_PRICE_SCALE hatasi dönüyor.

API içinde bu hassasiyet ayarı otomatik olarak yapılabilir mi?
BTC alırken basamak sayısı alacağımız değerin hassasiyetine göre ayarlanmalı.
ETH alırken float 201.1111 girdiğimizde API bunu otomatik olarak 201.1 e çevirmeli diye düşünüyorum.

En azından şuradaki fonksiyonu API ya eklemeniz yerinde olacaktır
https://api.btcturk.com/api/v2/server/exchangeinfo

**Comment by outlier-1** [comment]
Merhaba, biraz önce 1.0.7 Versiyonunu yayınladım.

Yeni versiyonda get_exchange_info adlı bir fonksiyon var, parametre olarak sembol listesi alıyor. Örnek kullanımı,
`client.get_exchange_info(['BTCUSDT', 'XRPUSDT'])`
Döndüğü listede verdiğiniz listedeki işlem çiftlerinin scale değerlerini de dönüyor. O değerleri kullanarak emir girmeden formatlamanızı yapabilirsiniz

**Comment by EUA** [comment]
Teşekkürler.
Formatlamaya amount da dahilmiş. Eğer almak/satmak istediğimiz miktar fazla kayarnoktalı ise bu sefer de FAILED_INVALID_QUANTITY_SCALE hatası veriyor...

Kullanici bunları kendisi de formatlayabilir elbet ama al/sat fonksiyonlarına şu şekil bir şey yerleştirmek herkesin hayatını daha da kolaylaştırmaz mı?
`price= "%0."+str([i for i in self.get_exchange_info() if i['name']==TradePair][0]['denominatorScale'])+'f' % price`

amount için de nasıl bir format uydurmalı bilemedim. 'numeratorScale' dek' kadar kayar noktaya izin veriyor sanırım. Onun 'için de benzer şekilde
`amount = "%0."+str([i for i in self.get_exchange_info() if i['name']==TradePair][0]['numeratorScale'])+'f' % amount`

Tabi her dafasında get_exchange_info çağırmaya gerek de yok. Veriler yerlerde statik olarak saklanabilirö init zamanında çekilebilir.

Benim oyum bu işlemleri kullanıcı koduna bırakmaktansa API içine yerleştirmek. Ha bir flag eklenerek raw değerler gönderilebilir de ... kim, neden böyle bir şey yapmak istesin bilemem...
Teşekkürler.

**Comment by outlier-1** [comment]
Tekrar merhaba, istediğiniz özelliği ekleyerek 1.0.8 versiyonunu şimdi yayınladım.

Artık girdiğiniz miktar ve fiyat parametreleri işlem çiftinin btcturkun belirlediği scale değerlerine göre otomatik olarak formatlanıyor. 

Fiyat veya miktar kısmında virgülden sonraki basamak kısmını düşünmeden istediğiniz emri girebilirsiniz.

Kolay gelsin.

**Comment by EUA** [comment]
Teşekkürler.

**Comment by EUA** [comment]
Haydi, bugün biraz Ripple alalım.

```
submit_limit_order( quantity=50, price=0.0000223545, order_type='buy', pair_symbol='XRPBTC' )

INVALID_REQUEST
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/btcturk_api/properties.py", line 11, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 878, in submit_limit_order
    return self.submit_order(params)
  File "/usr/lib/python3.8/site-packages/btcturk_api/properties.py", line 11, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 973, in submit_order
    return self._post(request_url, params)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 228, in _post
    self._handle_response(response)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 182, in _handle_response
    raise BadRequestError(response)
  File "/usr/lib/python3.8/site-packages/btcturk_api/exceptions.py", line 14, in __init__
    raise exception_class(response)
btcturk_api.exceptions.InvalidRequestParameterError: <Response [400]>
```

Sanırım son kod değişimi bir şeyleri bozdu...

**Comment by outlier-1** [comment]
İyi geceler, 

Ondalık sayısı çok düşük olunca bilimsel notasyona çeviriyormuş float gösterimi o sebeple hata alıyormuşsunuz.

Şimdi düzeltip 1.0.9 versiyonunu yayınladım.

Kolay gelsin

**Comment by EUA** [comment]
Bende çok sorun çıkarttım ama API baya güzel, dolu dolu oldu...
BTCTürk yerine olsam verir 1 BTC haklarını satın alırdım.
Teşekkürler.
