### ISSUE TITLE
Sunucu Zamanı

### ISSUE THREAD

**Issue by EUA** [outlier-1/btcturkapi-python#13]
İmlementasyonda sunucu zamanı bulunmamakta, eksik kalmasın. :)
https://api.btcturk.com/api/v2/server/time

**Comment by berkosko5000** [comment]
Günde birkaç kez atıp saatlerce almama sebebi bu mudur erdem abi,nasıl fiksleyebiliriz bir de biliyor musun?

**Comment by outlier-1** [comment]
Merhaba,

Sunucu zamanı ekledim.
```
client.get_server_time() #  Returns Direct Server Response
client.get_server_time(as_timestamp=True)  # Returns unix-timestamp integer 
```
1.2.0 Versiyonu ile birlikte yayında,
Paketi upgrade ederek kullanabilirsiniz.

**Comment by berkosko5000** [comment]
@outlier-1 süpersin hocam

**Comment by outlier-1** [comment]
@berkosko5000  
Birkaç kez atıp saatlerce almama durumundan kastınız nedir? Serverdan response mu alamıyorsunuz? Dahat detaylı açıklarsanız yardımcı olabilirim.
İyi çalışmalar

**Comment by berkosko5000** [comment]
Unauthorized yanıtı alıyorum.Terminalden girmeye çalıştığımda da aynı durumla karşılaşıyorum çözüm geliştiremedim

**Comment by outlier-1** [comment]
Unauthorized yanıtını tek başına almazsınız Unauthorized - {HATA MESAJI} şeklinde bir yanıt almanız gerekiyor, kütüphanenin güncel versiyonunu kullanıyorsanız şu tarz bir yanıt alabilirsiniz,

```
btcturk_api.exceptions.BTCTurkAuthenticationError: Authentication Error.
Server Response: Unauthorized - Invalid Nonce
```
Eğer Invalid Nonce hatası alıyorsanız server time ile isteği yaptığınız istemcinin zamanı uyuşmuyor demektir, sistem zamanının doğru olduğundan emin olmalısınız. Muhtemelen bu tarz bir hata alıyorsunuz.

Bir diğer ihtimal de yanlış api key bilgileri girmiş olmanız ama kontrol etmişsinizdir o yüzden sadece hatayı örnek olsun diye bırakıyorum.

```
btcturk_api.exceptions.BTCTurkAuthenticationError: Authentication Error.
Server Response: Unauthorized - Invalid Signature
```
Gördüğünüz gibi yanlış api-key girdiğinizde Invalid Nonce yerine Invalid Signature Hatası üretti.

Hangi hata mesajını alıyorsanız ona göre yorum yapabilirim

**Comment by berkosko5000** [comment]
Invalid nonce hatası alıyorum evet.

**Comment by outlier-1** [comment]
Rica ederim, bu konuyla ilgili size de yardımcı olacak bir patch yazıyorum şuanda güncelleyince haber vereceğim

**Comment by outlier-1** [comment]
Tekrar merhaba,
Versiyonu 1.3.1'e güncelledim.

Artık invalid nonce hatası alırsanız şu şekilde bir bilgi mesajı da iletilecek,

```
btcturk_api.exceptions.BTCTurkAuthenticationError: Authentication Error.
Server Response: Unauthorized - Invalid NonceYou have encountered Invalid Nonce Error.
This usually happens when your client's time and server's time are inconsistent.
Your computer's time is behind of servers time by 0:09:05.416589
```

Bu şekilde server ile olan zaman uyumsuzluğunuzu görebilir, bilgisayarınızın saatini ona göre ayarlayabilirsiniz.

**Comment by berkosko5000** [comment]
Çok teşekkürler hocam hemen kurulumu yapıyorum

**Comment by outlier-1** [comment]
Bu arada ben paketi güncellesem de siz şuan eski sürümü kullanıyorsunuz, elle güncellemeyi yapmanız gerekli.
Terminal erişiminiz varsa
`pip install --upgrade btcturk-api`
komutuyla ya da pycharm kullanıyorsanız proje kütüphanelerinden 1.3.1 sürümüne güncellemeyi unutmayın

**Comment by EUA** [comment]
Teşekkürler.
