### ISSUE TITLE
TRON TRX sembol hatası

### ISSUE THREAD

**Issue by EUA** [outlier-1/btcturkapi-python#14]
TRX USDT alıp-satarken hata 
```
File "btcturk_api/client.py", line 868, in submit_limit_order
scale = SCALE_LIMITS[pair_symbol.upper()]
KeyError: 'TRX_USDT' 

```

**Comment by outlier-1** [comment]
Merhaba, bu gece fixleyip çözüm atacağım. Bu postu editlerim
İyi çalışmalar

**Comment by outlier-1** [comment]
Tekrar kolay gelsin, scale limitlerini dosyadan okuyordu; yeni coin ekleyince dosyada o coinin bilgileri olmadığı için alıyordunuz hatayı da şimdi dinamik bir çözüm yazdım. 
Api ile her seferinde limitlere baktırmak aşırı yavaş olduğundan tek sefer okuyup dosyaya cache ederek oradan okumaya devam edecek. Paketi güncelleyerek kullanmaya devam edebilirsiniz

İyi çalışmalar

**Comment by EUA** [comment]
Ben bu bug reportu yapalı 15 (yazı ile on beş) gün mü geçmiş? Valla bu işte bi yanlışlık var...
Düzeltme için teşekkürler. :+1:
