### ISSUE TITLE
FAILED_INVALID_QUANTITY_SCALE (buy "BTCUSDT", "BTCTRY")

### ISSUE THREAD

**Issue by AsimCanALKAN** [outlier-1/btcturkapi-python#15]
Merhaba, öncelikle API hizmetiniz için çok teşekkür ederim. Ben bir market order gönderdiğim zaman "**sell**" yaparken sorunsuz işlem gerçekleşiyor ancak "**buy**" yaparken aldığım hata 400 kodlu ve API hizmetiniz **### **FAILED_INVALID_QUANTITY_SCALE**** hatasını dönüyor. Sebebi ne olabilir?

**Comment by outlier-1** [comment]
Merhabalar,

Şimdi test ettim ve metotlar çalışıyor, ama hata almanızın sebebi şu olabilir;

Sell metodunu çağırırken quantity yerine satmak istediğiniz bitcoin miktarını giriyorsunuz ve olması gerektiği gibi hata almıyorsunuz, ama btcturk api'yi tasarlayanlar buy yaparken bitcoin miktarı yerine kaç liralık almak istiyorsanız o tutarı girmenizi gerektirecek bir tasarım yapmış.   

Örnek vermek gerekirse

**0.5 Bitcoin market sell işlemi**
`client.submit_market_order(quantity=0.5, order_type='sell', pair_symbol="BTCUSDT")`

Siz eğer 0.5 bitcoin almak için submit market order metodunu şu şekilde çağırıyorsanız hata alırsınız;
`client.submit_market_order(quantity=0.5, order_type='buy', pair_symbol="BTCUSDT")`

Çünkü btcturk bu çağrıyı 0.5 usdt tutarında bitcoin almak olarak yorumluyor, bana sorarsanız hakikaten garip bir seçim ama böyle.

Onun yerine bitcoin almak istediğiniz tutarı para birimi olarak kullanmanız gerekiyor, 
500 liralık bitcoin almak için: 
`client.submit_market_order(quantity=500, order_type='buy', pair_symbol="BTCTRY")`

Bu ayrımı benim de dökümantasyona eklemem gerekiyor, vakit bulunca düzenleyeceğim.

Bu arada hatayı bu nedenle aldığınızı varsaydım bu nedenle almıyorsanız belirtin yardımcı olmaya çalışayım.

İyi çalışmalar.

**Comment by AsimCanALKAN** [comment]
Çok teşekkür ederim size hızlı cevabınız için, bu bilgiyi ben de göremedim bir yerde. Garip bir durum ancak dediğiniz gibi çözüldü sorun 😊

 

Asım Can ALKAN 
Phone: +90 537 214 7377
Email: alkanasimcan@gmail.com

**Comment by outlier-1** [comment]
Rica ederim, bu arada e posta imzanız nedeniyle telefon numarası gibi kişisel bilgileriniz son yaptığınız yoruma eklenmiş, ben siliyorum. E posta üzerinden cevap verirken dikkatli olun :)

İyi geceler.

**Comment by AsimCanALKAN** [comment]
Merhaba,

 

Öncelikle tekrardan API hizmetiniz için teşekkür ederim ancak benim bir sorunum var BTC API TEST hesabını kullanıyorum ancak MARKET emir gönderirken BUY metodunda hala sorun yaşıyorum girdiğim fiyata bazen emir gidiyor bazen emir gitmiyor sebebi ne olabilir, genellikle <FAILED_INVALID_QUANTITY_SCALE> bu hata ile karşılaşıyorum ancak bazen de bu emir gerçekleşiyor. Bu arada BTCTURK’un bu garip mantığı Market emire hiç uymuyor adet giremiyor olmak üzücü. Ancak bu sorun neden olabilir bazen emir gerçekleşiyorken bazen bu hatayı vermesi bana çok garip geliyor acaba BTCTURK’un Test sistemi bozuk olabilir mi?

**Comment by outlier-1** [comment]
Merhaba, eğer benim koduma direk müdahale etmediyseniz Btcturk'un test apisini kullanamazsınız. Test endpoint'i ile production endpointi birbirinden farklı.

Testnet için aldığınız (https://pro-dev.btcturk.com üzerinden) API-KEY, SECRET-KEY çiftini mi uygulamada kullanmaya çalışıyorsunuz?

**Comment by AsimCanALKAN** [comment]
Evet base url’yi değiştirdim sizin kodunuzda test edebilmek için daha sonra base url’yi değiştiricem sizce bu sorun test sistemi ile mi alakalı?

**Comment by AsimCanALKAN** [comment]
Aslında size sormak istediğim bir konuda mesela ben BTC/USDT almak istiyorum ancak MARKET BUY ORDER kısmında ben BTC miktarını direk giremiyorum ve fiyat girmem gerekiyor buradaki sorunum şu benim girdiğim fiyat ile gerçekleşecek miktarda satış yok ve aslında alış ortalama fiyatım bu sebeble arttı (2. Veya 3.kademeden alışlar da yaptım) ve alacağım miktar azalıyor. Ben burada direk BTC miktarını girebileceğim bir yol mevcut mu? Ve ekstra orderbook amounta falan da mı bakmam lazım?

**Comment by outlier-1** [comment]
Söylediğiniz hatayı şimdi farkettim. O satın alırken karşılaşıyorum dediğiniz hatayı btc-try işlem çiftinde alıyorsunuz değil mi?

Normalde yazılım girdiğiniz miktar ve fiyat değerlerini sunucuya yollamadan normalleştiriyor, yani btcturk'un istediği şekilde formatlıyor. Bu özellik de normal şartlarda kullanıcıyı virgülden sonra kaç rakam girmeliyim derdinden kurtarıyor.

Fakat yazılım bu formatlamayı yaparken virgülden sonra gereken rakam sayısını https://api.btcturk.com/api/v2/server/exchangeinfo adresinden öğreniyor, orada da nedense btc-try çiftinde payda scale i 2 olarak girilmiş ama 0 olarak bekliyor. Tabi program 2'yi denediği için hata alıyorsunuz.

Bir kahve koyup bu sorunu çözecek bir patch yazacağım şimdi. Yayınladığımda buraya bildireceğim.

Son söylediğiniz içinse çözüm limit order kullanmak, orada almak istediğiniz fiyatı da giriyorsunuz böylelikle sürpriz olmamış oluyor. Market order kullanırsanız o anki fiyat kaçsa o fiyattan alırsınız ya da satarsınız o sebeple şansa kalmış oluyor.

**Comment by outlier-1** [comment]
> Aslında size sormak istediğim bir konuda mesela ben BTC/USDT almak istiyorum ancak MARKET BUY ORDER kısmında ben BTC miktarını direk giremiyorum ve fiyat girmem gerekiyor buradaki sorunum şu benim girdiğim fiyat ile gerçekleşecek miktarda satış yok ve aslında alış ortalama fiyatım bu sebeble arttı (2. Veya 3.kademeden alışlar da yaptım) ve alacağım miktar azalıyor. Ben burada direk BTC miktarını girebileceğim bir yol mevcut mu? Ve ekstra orderbook amounta falan da mı bakmam lazım?

Direkt olarak  limit order metotlarını şu şekilde kullanabilirsiniz:
134.000 TL fiyatından 0.52 Bitcoin Satın almak için:
`client.submit_limit_order(quantity=0.52, price=134000, order_type="buy", pair_symbol="BTCTRY")`

135.000 TL fiyatından 0.52 Bitcoin Satmak için:
`client.submit_limit_order(quantity=0.52, price=135000, order_type="sell", pair_symbol="BTCTRY")`

**Comment by outlier-1** [comment]
Tekrar merhaba,

1.5.1 sürümüyle scale hata çözüldü. 

Paketi güncelleyip kullanabilirsiniz.

**Comment by AsimCanALKAN** [comment]
Son kısımla alakalı şöyle bir sorun var ama ben BTC/USDt işlem çifti ile işlem yapıyorum ve BTC alış yapacağım burada benden USDt miktatı girmem isteniyor BTC alırken ben de şunu istiyorum MARKET emir kesinlikle olmalı çünkü işlemim hızlı gerçekleşmeli ancak ben istiyorum ki alacağım BTC Miktarını gireyim ve fiyat ne bilmeme gerek olmadan neyse fiyat o fiyattan işlemi gerçekleştireyim. 
Yani BUY yaparken de SELL yaparken yaptığım gibi BTC miktarı girmek. Öbür türlü benim alacağım miktar market emirde değişiklik gösterecek. Yani amacım BTC miktarını sabit tutmak BTC alırken. 

Von meinem iPhone gesendet

**Comment by AsimCanALKAN** [comment]
Çok güzel ancak market order da ben buy yaparken BTC miktarını değil de USDt miktarını girmem gerekiyor bu da bana şu sorunu yaratıyor market orderda alacağım BTC miktatını kesin olarak belirleyemiyorun. Çünkü satış fiyat kademesindeki amountlar değişiyor az veya çok oluyor. Ben fiyat girdiğimde orada Execute edilecek ortalama fiyat ile benim btc miktarım belli oluyor bu da sorun. Market orderda nasıl bir çözüm geliştirilebilir?
Ayrıca elinize aklınıza emeğinize sağlık patch için. 

Von meinem iPhone gesendet

**Comment by outlier-1** [comment]
>  BTC alırken ben de şunu istiyorum MARKET emir kesinlikle olmalı çünkü işlemim hızlı gerçekleşmeli ancak ben istiyorum ki alacağım BTC Miktarını gireyim ve fiyat ne bilmeme gerek olmadan neyse fiyat o fiyattan işlemi gerçekleştireyim. Yani BUY yaparken de SELL yaparken yaptığım gibi BTC miktarı girmek.

Öncelikle market emri şart diyorsanız quantity USDT veya TL veya olmalı, btcturk başka türlü kabul etmiyor.

Şöyle bir tradeoff durumu var, market emri kullanırsanız hız avantajınız olur ama fiyata müdahale edemezsiniz, limit emri kullanırsanız neyi hangi fiyattan aldığınızı bilirsiniz ama emri kapatıp kapatamayacağınızın garantisi yok, ona göre hamle yapmanız gerekiyor.

Peki ne yapmalıyım sorusu da yazılım probleminden çok danışmanlığa giriyor, o konuda da maalesef buradan yardımcı olamam. Artıları eksileri göz önünde bulundurarak sizin karlı bir çözüm geliştirmeniz gerekli. Ben kendi kripto botumda bu şekilde bir çözüm uyguluyorum. 

Yazılım ile ilgili problem yaşarsanız tekrar issue açabilirsiniz, vakit buldukça ilgileniyorum.

Scale bug'ı çözüldüğü için bu issue'yu kapatıyorum.

İyi çalışmalar.

**Comment by AsimCanALKAN** [comment]
FAILED_ORDER_WITH_OPEN_ORDERS merhaba Ömer Bey bu hatanın sebebi ne olabilir ?

 

Asım Can ALKAN 
Phone: +90 537 214 7377
Email: alkanasimcan@gmail.com

**Comment by outlier-1** [comment]
Emri gerçekleştirmek için bakiyeniz yetersiz olduğunda o hatayı alıyor olmalısınız, ucu ucuna bakiyeyle market emri veriyorsanız almanız olası

**Comment by AsimCanALKAN** [comment]
Teşekkür ederim 😊

**Comment by AsimCanALKAN** [comment]
Merhaba Ömer Bey,

BTCTURK tarafından yeni bir endpoint eklenmiş olabilir, ben birkaç talep oluşturmuştum ancak sizin API’nizde mevcut değil belki bir kontrol etmek istersiniz. Gelen cevap:” Belirtmiş olduğunuz seçenek Endpoint /api/v2/account/advanced-order-history average sekmesinde mevcuttur.”. Sanırım bir şeyler düzeltirken get_all_order uç noktasını bozdular ve 500 Internal hatası veriyor.

Teşekkürler

 

 

Asım Can ALKAN 
Phone: +90 537 214 7377
Email: alkanasimcan@gmail.com
