### ISSUE TITLE
Quantity Kusurat Degistirirken Yukari Yuvarlama

### ISSUE THREAD

**Issue by onurece** [outlier-1/btcturkapi-python#23]
Merhaba,

Asagidaki sekilde emir girmeye calistigimda, API quantity'nin decimal pointini 2 yapiyor ve formatted_qty 3.25 oluyor.
```
client.submit_limit_order(
    quantity=3.246254185436819,
    price=173.31,
    order_type='buy',
    pair_symbol='ATOM_TRY'
)
```

Fakat hesabimda sadece 3.24'luk alim yapabilecek para oldugunda hata aliyorum. Bunun yerine asagidaki sekilde rounding olmadan ekstra kismi kesip atmaniz mumkun mu? 

```
import math

quantity=3.246254185436819
amount_scale=2

str(math.floor(quantity * 10**amount_scale)/(10**amount_scale))
```
Kodun tutarli olmasi icin aynisi fiyat yuvarlamasinda da yapilabilir ama onunla ilgili bir sorunum yok.

**Comment by outlier-1** [comment]
Selamlar @onurece ,

ATOM/TRY işlem çifti miktar olarak yalnızca 2 ondalık basamak destekliyor, girdiğiniz değeri server'a yollamadan önce formatlamak zorundayım ki hata almayın. Bu sayede her emir çifti için ayrı ondalık basamaklarıyla uğraşmanıza gerek kalmadan işlem yapabiliyorsunuz. 

Ancak, karşılaştığınız durum gibi ondalığın yukarı yuvarlanması sebebiyle hata almanız konusunun çözülmesi gerektiğini düşündüm ve yukarı yuvarlama yerine aşağı yuvarlama yapılması çözümünü mantıklı buldum

Biraz önce yeni bir patch yayınladım, pip üzerinden de paketi güncelledim. 

1.8.1 sürümü itibariyle girdiğiniz fiyat ve miktar metrikleri truncate edilirken aşağı yuvarlanacak. 

`pip install --upgrade btcturk-api `

Komutu ile python paketini güncelleyip kullanmaya devam edebilirsiniz.

**Comment by onurece** [comment]
Bu kadar hizli guncelleyeceginizi hic beklemiyordum. Cok tesekkurler. Ayrica sayenizde decimal library sini ogrenmis oldum.
