### ISSUE TITLE
Failed Minimum Amount

### ISSUE THREAD

**Issue by berketurker14** [outlier-1/btcturkapi-python#27]
client = Client(key,secretkey)
client.submit_market_order(quantity=15, order_type='buy', pair_symbol='DASHTRY')
//pairde DASH_TRY de denedim

FAILED_MIN_TOTAL_AMOUNT 
btcturk_api.exceptions.InvalidRequestParameterError: <Response [400]>
Almakta olduğum hata bu

quantity'nin birimi Türk Lirası

market_orderda bir hata mı var benim hatam mı bilemedim.
Şimdiden teşekkürler.

**Comment by outlier-1** [comment]
Selamlar, hayır kodunuzda herhangi bir problem yok.

DASH/TRY işlem çifti için minimum tutarın altındasınız sadece. Türk lirası ile dash almak istiyorsanız bir trade'de minimum 100 liralık alabilirsiniz. 15 liralık almaya çalıştığınız için hata alıyorsunuz.

Bu tutara nereden baktığımı merak ediyorsanız:
pairs = ["DASHTRY"]
client.get_exchange_info(pairs)

Dönen cevap içinde "minExchangeValue" ye bakarsanız 99.91 olduğunu göreceksiniz. Yuvarlayıp 100 lira dedim o sebeple.

**Comment by berketurker14** [comment]
Çok teşekkürler :)
