### ISSUE TITLE
limit_order

### ISSUE THREAD

**Issue by oktayoki** [outlier-1/btcturkapi-python#28]
aşağıdaki gibi bir komut veriyorum örneklerinize bakarak ama parametrelerim hatalı gibi bir hata veriyor

    my_client.submit_limit_order(
        quantity=0.00024975,
        price=100.0,
        order_type='buy',
        pair_symbol='BTC_TRY'
    )

100 TL ile 0.00024975 BTC almaya çalışıyorum

**Comment by outlier-1** [comment]
Selamlar,
Limit order’ın işleyişi market order’dan farklıdır. 
Limit order fiyat X’e gelince o fiyattan Y kadar alım/satım emri gir demektir.

Sizin örnek kodunuzun türkçeye çevirisi şu: 

Bitcoin’in fiyatı 100 TL’ye düşerse 0.00024975 adet bitcoin için birim başı 100 TL’den alım emri gir.

Limit order girmek için hedef fiyat belirlemeniz gerekiyor.

Aşağıdaki kod şunu yapar örneğin: 
Bitcoinin fiyatı 250.000 tl’ye düşerse 250.000 liradan 0.00024975 bitcoin için alım emri gir.

my_client.submit_limit_order(
    quantity=0.00024975,
    price=250000,
    order_type='buy',
    pair_symbol='BTC_TRY'
)

Umarım açıklık getirebilmişimdir

**Comment by oktayoki** [comment]
Selamlar,
anladım. BTCTurk te limit emri verirken BTC nin 380000 TL ye düştüğünde 100 TL lik al diyebilyoruz ama burada BTC 380000 TL ye düştüğünde 0.00024975 kadar BTC al dememiz gerekiyor. 

teşekkürler

**Comment by outlier-1** [comment]
Aslında BTCTurk web arayüzünde de aynı. BTC/TRY işlemi için limit seçeneğine tıklarsanız sizden "Almak istediğiniz fiyat" ve "Almak istediğiniz miktar" girdilerini istiyor. API'da da aynı şekilde fiyat ve miktar giriyorsunuz.

Rica ederim, iyi çalışmalar
