### ISSUE TITLE
Nonce must be greater than ...

### ISSUE THREAD

**Issue by EUA** [outlier-1/btcturkapi-python#5]
Ara yüzden elle denediğimde bir sorun çıkartmadıydı.
Elle bi nonce girişi yapmadım parametre olarak.
Program içerisinde yapınca böyle bir hata ile karşılaştım.
Sistemin saati de güncel ama...

```
    a=self.api.submit_limit_order( quantity=amount, price=pricebuy, order_type='buy', pair_symbol=TradePair )
  File "/usr/lib/python3.8/site-packages/btcturk_api/properties.py", line 11, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 747, in submit_limit_order
    return self.submit_order(params)
  File "/usr/lib/python3.8/site-packages/btcturk_api/properties.py", line 11, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 831, in submit_order
    return self._post(request_url, params)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 232, in _post
    self._handle_response(response)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 186, in _handle_response
    raise BadRequestError(response)
  File "/usr/lib/python3.8/site-packages/btcturk_api/exceptions.py", line 14, in __init__
    raise exception_class(response)
btcturk_api.exceptions.InvalidRequestParameterError: <Response [400]>
Nonce must be greater than 1587950598259999. You provided 1587950292585575.
```

**Comment by EUA** [comment]
> NOTE: It is a must to sync your current time with API server time which is in miliseconds format. Our servers are using UTC timezone.

Sanırım sistem saati ile aradaki fark hesaplanıp her çağrıya offset olarak eklenmesi gerekiyor.

**Comment by outlier-1** [comment]
Merhaba, https://api.btcturk.com/api/v2/server/time linkinden server saati ile sizin güncel saatinizi kontrol edebilir misiniz? Gönderdiğiniz timestamp server saatinden 5 dakika önce görünüyor.

**Comment by EUA** [comment]
Sistem saatimde herhangi bir sorun yok. NTPDate.
İşin garibi python ile girip al-sat yapabiliyorum sorunsuz şekilde.
Program içerisinde dönerken al-set işleminde bu sorunu yapıyor ama.
Sistem saati sorun olsa elle fonkisyon girdiğimde de alım satımda aynı sorunu çıkartması lazım.
Fonksiyonda gönderilen nonce, belki başka kullandığım kütüphanelerin nonce değişkeni ile karışıyor olabilir mi isim benzerliğinden dolayı? Bir tek bu geliyor aklıma. Bir daha yakalarsam iyice içine dalacağım

**Comment by outlier-1** [comment]
Python ile sorunsuz al sat yapabiliyor ama programınızda hata alıyorsanız muhtemelen program akışınızda kütüphanenin düzgün çalışmasını engelleyen bir durum vardır. Kodunuzu göremediğim için buradan bu kadar yorum yapabiliyorum. Yine de anlattıklarınızdan yola çıkarak birkaç yorum yapayım.

Farkettiğim bir detay siz server'a mikrosaniye cinsinden bir timestamp yolluyorsunuz. 
Benim kütüphanemin ise normal şartlarda timestampi milisaniye cinsinden üretip servera yollaması gerekiyor. API'nin server time endpointinde bile server timestampi milisaniye olarak dönüyor.

Eğer server sizin yolladığınız değeri mikrosaniyeye çevirip bunu gönderdiniz şeklinde söylemiyorsa ki serverın timestampinin milisaniye üzerinden dönüş yaptığını göz önünde bulundurursak bu zor bir ihtimal, servera gönderdiğiniz timestampin kütüphanede üretilenle aynı olmama ihtimali var.

Programınızın oluşturduğunuz clientin kullandığı Session'ın Headerında "X-Stamp" alanına bir şekilde müdahale ediyor olması mümkün mü kontrol edebilirsiniz.

Son olarak çok uçuk bir ihtimal ama multithreading bir yapı kullanıyorsanız submit_limit_order metodunun çalışması esnasında başka bir metodun araya girerek onu bloke etmediğinden emin misiniz? Başka bir metot global interpreter lock'u bırakmıyorsa ya da sizin tasarladığınız bir durumdan dolayı metodun çalışması sekteye uğruyor olabilir ama bu ihtimal üstte değindiğimden daha düşük bir ihtimal.

Yine de ben sorunun server'a gönderdiğiniz timestampin kütüphanemde üretilen timestamp olmadığından kaynaklandığını düşünüyorum. O alanda debugging yapmanızı öneririm.

**Comment by EUA** [comment]
Hımmm. mikro/mili saniye formatı farkı bence bu sorunu açıklar. Bunu nereden anladınız onu da bilemiyorum. Güzel bir fark ediş ama. Peki bu durum her zaman hata vermemesini de açıklıyor mu?

Ben Arch Linux üzerinde python3.8 ile kullanıyorum. Farklı os tabanlı yada versiyon python kütüphaneleri yüzünden bu fark ortaya çıkıyor olabilir mi? Zannediyorum Windows milisaniye, Linux ise mikrosaniye kullanıyor yüksek hassasiyetli zamanlama için default olarak. Python da platformların defaultlarını almayı sevdiğinden sebebini bulmuş olabiliriz...

Bu ara thread içinde "get_account_balance()" yaptığımda yakalıyorum bazen. Ama threadın toplam çalışma süresi 1 sn. Ana kodu url request ile bekletmesin diye öylesine açılmış bir thread. Bundan kaynaklanıyor olabileceğini pek düşünmüyorum ben de.

Teşekkür ederim.

**Comment by outlier-1** [comment]
Öncelikle nasıl farkettiğimi açıklayayım, Timestamp dediğimiz kavram 1 ocak 1970 UTC'den günümüze kadar geçen toplam saniye sayısını ifade ediyor. Günümüz tarihinde bu sayı 10 basamaklı, milisaniye bazına çevirmek isterseniz 10 üzeri 3 ile çarpılacağından 13 basamaklı, mikrosaniye ise 16 basamaklı olmalı. Bu şekilde anladım mikro ve milisaniye farkını.

Platform ya da python kütüphaneleri yüzünden olma yaklaşımına gelirsek, ben de kendi yazılımımı bir ubuntu linux sunucusunda çalıştırıyorum. Timestamp dediğimiz kavram da özünde unix timestamp olarak geçtiğinden farklı os tabanlı olma durumundan olduğunu düşünmüyorum.

Ancak python 3.8'e geçiş yapmadığım için o konuda emin değilim, emin olmak için aşağıdaki adımları takip etmenizi isteyeceğim,

- Python'un 3.6.9 sürümünü kurun
- Bir virtual environment oluşturup `sudo pip install btcturk_api `komutuyla kütüphaneyi kurun. 
- Bir ihtimal de kütüphanenin bağlı olduğu requests gibi ek kütüphanelerin farklı sürümlerinin sisteminizde kurulu olması olabilir, bunu engellemek için temiz bir virtual environment kullanmanızı tavsiye ediyorum.
- Temiz virtual environment'a bu kütüphane ve kendi ek kütüphanelerinizi kurduktan ve python'un 3.6.9 sürümüyle çalıştırdıktan sonra aynı hatayı alıp almayacağınızı gözlemleyebilirsiniz

. 

Gözlem sonuçlarından beni haberdar ederseniz sevinirim, sorunun kaynağını bulursak dökümantasyonuma ekleyeceğim.

Geri dönüşünüzü bekliyorum,

İyi çalışmalar

**Comment by EUA** [comment]
Python 3.6 yüklemek külfetli bir işlem benim açımdan.
Şimdilik bundan kaçınıyorum. Ama henüz sorun neden kaynaklanıyorun peşini bırakmadım.
Biraz uğraştım, söyle bir sonuca ulaştım.
Programımın çalıştırıldığı tarihi kayıt edip aradan epey zaman geçince bir API işlemi yapayım dedim;
Çalıştırılan fonksiyon get_account_balance():

> [death@Ryzen ExBot]$ date; ./bot.py 
> Çrş 29 Nis 2020 06:27:44 +03
> 
> Nonce must be greater than 1588167195818999. You provided 1588130866014401.
> 
> Wednesday, April 29, 2020 6:27:46.014 AM
> Wednesday, April 29, 2020 4:33:15.818 PM

Nedense, gönderilen nonce programın çalıştırıldiğı ilk zamanda üretilmesi gereken nonce. Fonksiyonun çağırıldığı anda üretimesi gereken nonce değil. get_account_balance() fonksiyonu da thread içerisinde, hatta 2-3 thread içerisinde çağırılıyor. Ama tabiiki threadın bu fonksiyonun çağırışında saatlerce kesintiye uğraması söz konusu değil. Garip bir durum var. Başka bir olağandışılık görür isem bildiririm.

**Comment by outlier-1** [comment]
Bunu farketmeniz güzel oldu. 
Programın ilk çalıştırıldığı dediğinizde ne kastettiğinizi bilirsem daha rahat anlaşılır tabii, programın ilk çalıştırılması demek
` client = Client(key, secret) şeklinde `
api clientinden bir nesne oluşturmanız ama bir emir vermemeniz demek mi? 
Çünkü bu client nesnesini oluşturduğunuz an program bir nonce üretip get_account_balance fonksiyonunu çağırıyor verdiğiniz api bilgilerinin doğruluğunu kontrol etmek için.

Yoksa programınızın çalışmasının ilk anında böyle bir şey yok mu, dediğiniz gibi uzun bir zaman geçtikten sonra emir gireceğiniz an mı oluşturuyorsunuz Client() nesnesini?

**Comment by EUA** [comment]
Program açılışında bir nesne oluşturup sürekli aynı nesneyi kullanıyorum. Belirli aralıklarla orderBook çekiyorum. Ama herhangi bir emir vermiyorum. Hata da almıyorum. Uzun bir süreden sonra tekrar bir thread içerisinde get_account_balance çağırınca bu hatayı veriyor... Sanki nonce yi alıp bir sonraki sorgu için bekletiyor mu ... anlamadım. Belki de hali-hazırdaki python kütüphanelerimde bir sıkıntı vardır. Tam bilemiyorum, arada sırada açar müdahale eder, kirletirim. Çünkü başka API lar farklı özellikler vs istiyor. Bir ara requests'e bulaşmışım gibi hissediyorum... En iyisi temiz bir virtual env de yeniden yükleyeyim, yapabilirsem sorunu gösteren mini-sample kodlayayım. Eğer sorunu programımdan ayırıp tek başına örneklendirebilir isem buraya tekrar bildirimde bulunurum. Nasılsa şu an çalışmayı pek engellemiyor. İlgilendiğiniz için teşekkür ederim.

**Comment by EUA** [comment]
Debug ederken hatanın kütüphaneden kaynaklanmadığını keşfettim. Teşekkürler.

**Comment by outlier-1** [comment]
Bilgilendirdiğiniz için teşekkürler, hatanın kütüphaneden kaynaklanmadığına sevindim. Yalnız merak ettim sonuçta birkaç gündür düşünüyoruz, sakıncası yoksa neden kaynaklandığı konusunda bilgi verebilir misiniz?

**Comment by EUA** [comment]
Nereden kaynaklanıyor tam olarak sorun çıkaran koda bakmadım.
Sorun başka API bağlantılarından kaynaklanıyor diye tahmin ediyorum.
Fakat BTCTurk API eklemeden önce bu tip bir sorunla karşılaştığımı hatırlamıyorum.
BTCTurk APIda InvalidRequestParameterError sorun verince nonce yüzünden zannettim.
Bkz şu çıktı çok yanıltıcı.

```
btcturk_api.exceptions.InvalidRequestParameterError: <Response [400]>
Nonce must be greater than 1587950598259999. You provided 1587950292585575.

```
Kesin konuşmayayım ama şu anki düşüncem, Nonce hata satırının başka bir Thread içerisinden atılmış bir hata çıktısı olduğu yönünde. Exception kesince sonuna eklemiştir heralde. BTCTurk API'yı izole edip çalıştırdığımda bir hata almadım çünkü. Artık tek tek deneyip bulacağız.
