### ISSUE TITLE
All Orders orderID missing

### ISSUE THREAD

**Issue by EUA** [outlier-1/btcturkapi-python#7]
API ya göre sanki ID girerek emrimizin sonucunu öğrenmemiz gerekiyor.
Ama get_trade_history() de parametre listesinde orderId girebileceğimiz bir seçenek yok.

Her ne kadar gelen listede emirleri görebilsek de, gelen listedeki ID ... Sanki order'den dönen ID dekinden farklı bir ID ye benziyor. Parametre olarak eklenmemesinin sebebi bu mu?
BTCTurk API da tutarsızlık mı var?

**Comment by outlier-1** [comment]
BTCTurk API get_trade_history() fonksiyonu için yalnızca trade türü, kripto sembolü ve tarih parametreleri alıyor evet, ama yanlış anlamadıysam amacınız açtığınız emrin nasıl sonuçlandığını öğrenmek. Bu iş için genelde get_open_orders() metodunu tercih ediyorum. 
Aşağıya birkaç senaryo ve çözümleri için küçük kod blokları bırakıyorum, umarım işinizi görür.

Senaryo 1- Order id'niz `order_id` adlı değişkende tanımlı ve integer, BTC-USDT çiftinde bir satış emri açtınız ve bu emrin tamamen kapanıp kapanmadığını öğrenmek istiyorsunuz. Tek satırda öğrenebilirsiniz

`closed = any([order['id'] == order_id for order in a.get_open_orders('BTC_USDT')['asks']])`
closed eğer emriniz kapandıysa False, hala açıksa True'dur. Daha sonra bu bilgiyi programınızda kullanabilirsiniz.

Senaryo 2 - Bu sefer emrin yalnızca tamamen kapanıp kapanmadığını değil, hala açıksa ne kadarının satıldığını, emrin ne kadarının tamamlandığını görmek istiyorsunuz. Yine tek satırlık çözümü şu şekilde olur.

`my_order = [order for order in a.get_open_orders('XRP_USDT')['asks'] if order['id'] == order_id][0]`

my_order değişkeni eğer None'sa emriniz kapanmıştır, değilse bir dictionary'dir ve emrinizle ilgili güncel bilgiler içermektedir. get_open_orders() fonksiyonunun dökümantasyonundan dictionary'deki alanların neler olduğunu görebilirsiniz.

Probleminizi çözdüğümü düşünüyorum, eğer probleminizi yanlış anladıysam belirtirseniz ona da çözüm üretip sizinle paylaşırım

**Comment by EUA** [comment]
Özellikle https://docs.btcturk.com/#all-orders deki API fonksiyonu için konuşuyorum. (yada [şu](https://github.com/BTCTrader/broker-api-docs/blob/master/README-pro.md#all-orders-requires-authentication) fonksiyon )
API'nın illaki bu fonksiyonu 1:1 eşleşme şeklinde kullanması olması gerekir ki API tamamlansın.
get_all_orders() fonksiyonu eklemeye değer diye düşünüyorum. Ben get_trade_history()' nin aynı işi yapacağını düşünmüştüm.

Açık emirlere tabiiki söylediğiniz şekilde ulaşabiliriz.
Peki ya kapatılan emirlere ait detaylı bilgiler ne olacak?
Gün sonunda hangi emirimizin ne kadar iyi iş yaptığını ne şekilde öğrenebileceğiz?
Burada gözardı edilemeyecek kadar çok entropi var.

**Comment by outlier-1** [comment]
O fonksiyon gözümden kaçmış api kütüphanemde eksik görünüyor. 
get_trade_history() şu fonksiyonu söylediğiniz api fonksiyonunu kullanmıyor, şu fonksiyonu kullanıyor: 
https://docs.btcturk.com/#user-transactions buranın içerisindeki /trade endpointini.

All orders fonksiyonunu 1 saat içerisinde yapacağım bir güncellemeyle ekleyeceğim

**Comment by outlier-1** [comment]
> Ayrıca, submit_limit_order tarafından döndürülen yapıdaki 'id' ile get_trade_history() sonuçlarında bulunan "id" birbirinden farklı. Bu da sizin API'nız yüzünden değildir heralde, değil mi? Buradaki ID heralde orderID değil de aslında emirle bir bağıntısı olmayan başka bir ID, mesela tradeID olsa gerek diye tahmin ediyorum. Sanırım orjinal API dokümanında da hata var.

Bu konuda haklısınız, oradan dönen id'nin kütüphaneyle ilgisi yok, order id ile trade id birbirinden farklı oluyor bu durumu ben de farketmiştim btcturk api'n kendisiyle ilgili bir durum. Zannedersem order kapanıp trade halini alınca yeni bir id atanıyor o yüzden birbirinden farklı

**Comment by outlier-1** [comment]
get_all_orders() fonksiyonu da 1.0.5 versiyonuyla birlikte eklendi.
API'da üzerine konuştuğunuz all orders fonksiyonun getirmesi gereken bilgileri getiriyor.

Fonksiyonun kullanımı için dökümantasyonuna bakabilirsiniz

**Comment by EUA** [comment]
Teşekkür ederim.

**Comment by EUA** [comment]
Tekrar merhabalar.
**order_id**, verilen order_id için değil de sonraki order için sonuç veriyor. Eşit olduğu emri döndürmüyor.

```
        order_id: int, optional
            If orderId set, it will return all orders greater than or equals to this order id
```

**Comment by outlier-1** [comment]
Merhaba, btcturk api dökümantasyonunda maalesef bu şekilde belirtilmiş, ben de ona göre yaptığım için ona göre sonuç veriyor.

Düzeltmeyi yapıp 1.0.6 versiyonunu yayınladım, artık eşit olan emri de döndürmeli.

**Comment by EUA** [comment]
Aslinda BTCTürk'den kaynaklandığını sezinledim ama...
Türkiyenin gerçeği işte. İşi layık olana değil de eşe dosta akrabaya yaptırmaya kalkınca böyle sıkıntılar çıkıyor. İşi bilmeyenler iş sahibi, işi bilenler işsiz kalıyor... Neyse çok konuşmayayım da twitterden sonra github hesabımı da kapattırmasınlar haksız yere...
Teşekkür ederim.
