### ISSUE TITLE
get_trade_history() obje yaratıldıktan sonra yapılan işlemleri içermiyor.

### ISSUE THREAD

**Issue by EUA** [outlier-1/btcturkapi-python#8]
get_trade_history() fonksiyonundan dönen değerler nedense BTCTurk.api.client.Client objesi yaratıldıktan sonra yapılan işlemleri içermiyor.

Objeyi yaratıp bir düşük işlemli al/sat yapıldığında işlemin get_trade_history() de gözükmesi lazım diye düşünüyorum. Ama nedense bu olmuyor. Üsterlik aynı obje tarafından al-sat yapılsa bile... Sadece client objesi yaratıldıktan önceki yapılmış olan sonuçları döndürüyor.

**Comment by outlier-1** [comment]
Yakaladığınız için tebrik ederim çok güzel yakalamışsınız.

5 dakika önce yayınladığım 1.0.3 versiyonunda bu bug çözüldü. 
Paketi upgrade edebilirsiniz
