### ISSUE TITLE
get_trade_history parametre hatası

### ISSUE THREAD

**Issue by EUA** [outlier-1/btcturkapi-python#9]
get_trade_history fonksiyonunda end_date kullanıldığında INVALID REQUEST hatası alıyorum.

```
>>> btr.api.get_trade_history( end_date=time.time()-3600 ) 
INVALID_REQUEST
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/btcturk_api/properties.py", line 11, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 475, in get_trade_history
    history = self._get(request_url, params)
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 208, in _get
    self._handle_response(response) # TODO: Need to raise exception (like _post), if error occurs
  File "/usr/lib/python3.8/site-packages/btcturk_api/client.py", line 184, in _handle_response
    raise BadRequestError(response)
  File "/usr/lib/python3.8/site-packages/btcturk_api/exceptions.py", line 14, in __init__
    raise exception_class(response)
btcturk_api.exceptions.InvalidRequestParameterError: <Response [400]>
```
tımestamp olarak **float** döndürülmesinden pek hoşlanmıyor galiba.**int** yaptığımda bu hatayı vermiyor. Fakat int dediğimde de anlamlı bir sonuç döndüremedim.
start_date ve end_date parametreleri fonksiyonel mi acaba? Son 1 saatlik veri için:
`btr.api.get_trade_history( start_date=int(time.time()), end_date=int(time.time()-3600))`
deniyorum ama... boş küme geliyor nedense.

**Comment by outlier-1** [comment]
Start ve end kavramlarını ikimiz farklı anlamışız sanırım :)

Start date ilk başladığı tarihi söylüyor, yani 1 saat önceden bahsediyorsanız o timestampi buraya girmelisiniz.
End date ise son tarih oluyor, örneğin tam şuanın zamanı. Yani ileri olan tarih burası olmalı. 
Verdiğiniz kodda boş küme dönmesi normal çünkü tam isteği yolladığınız saniyeden ilerisine bakıyor  yapılan tradeleri filtrelemek için.

Ek olarak,
btcturk her yerde milisaniye bazında timestamp kullanıyor. int(time.time()) kullanırsanız saniye bazında bir milisaniye elde edersiniz. Anın timestampini elde etmek için int(time.time()*1000) kullanırsanız daha sağlıklı olur. Sizin metodunuz da çalışır muhtemelen ama olası çıkabilecek hatalardan kaçınmak için böyle uygulamanızı öneririm.

Son olarak, son x saatin veya y günün verisini almak için elle çıkarma yapmak yerine timestampte hata olmaması için datetime kütüphanesini kullanırsanız hem kodunuzu daha rahat okursunuz hem de daha rahat sonuç alırsınız. 

Son 1 saatin trade verilerini şöyle alabilirsiniz:

```
import datetime as dt
timestamp = dt.datetime.timestamp(dt.datetime.now() - dt.timedelta(hours=1))
start_date = int(timestamp * 1000)
btr.api.get_trade_history( start_date=start_date, end_date=int(time.time()*1000)
```
Biraz yoğundum kusura bakmayın bu soruna geç dönebildim.

Kolay gelsin

**Comment by EUA** [comment]
Hımm. Evet çok farklı taraflardan bakmışız.
Benim için önemli olan son 3-5 dakika aslında. O yüzden koca datetime çekmeye gerek yok.

Pekiyi, timestamp float olarak girilmiş ise onu float'dan milisaniyeye otomatik çevirsek daha iyi olmaz mı API açısından? Evet bu şekilde de güzelö doğru ama kullanıcılar benim gibi detaylara dikkat etmeden time.time() kullanacaktır illaki diye düşünüyorum. Burası da opsiyonel olarak doldurulabilir bir "pitfall" bence.
